name: CI test for GITHUB

on:
  push:
    branches: [ master ]

#jobs:
#
#  build:
 #   runs-on: ubuntu-latest
    
  #  steps:
 #   - uses: actions/checkout@v2

#  Deploy:
 #   runs-on: ubuntu-latest
    
 #   steps:
 #     - uses: actions/checkout@v2 
 #     - name: Deploy in EC2
      
  #      env:
  #          PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
   #         HOSTNAME : ${{ secrets.HOSTNAME  }}
 #           USER_NAME : ${{ secrets.USER_NAME  }}
            
    #    run: |
          
 #         ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
     #      chmod -R 700 /home/ubuntu/
    #       cd /home/ubuntu/ &&
   #        mkdir testapp
   
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          #port: ${{ secrets.PORT }}
          run: |
            #cd /srv/shiny-server/${{ secrets.APPNAME }}
            mkdir /home/ubuntu/mytestapp
            #git pull
   
   
   
          '
